# Generated by Django 5.0.2 on 2024-06-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterModelTable(
            name='centre',
            table='Centers',
        ),
        migrations.AlterModelTable(
            name='etudiant',
            table='Etudiants',
        ),
        migrations.AlterModelTable(
            name='professeur',
            table='Professeurs',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
