# Generated by Django 5.0.2 on 2024-06-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('professeur', 'Professeur'), ('centre', 'Centre')], default='etudiant', max_length=20),
        ),
    ]
