# Generated by Django 5.0.2 on 2024-06-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meet_link', models.URLField()),
                ('created_by', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('agenda', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
